# Generated by Django 2.2 on 2020-05-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_img',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
